{application, ${ARTIFACT},
  [{description, ${DESCRIPTION}},
   {id, ${ID}},
   {vsn, ${VERSION}},
   {modules, ${MODULES}},
   {maxT, infinity},
   {registered, ${REGISTERED}},
   {included_applications, [${APPLICATIONS}]},
   {applications, [kernel,stdlib,sasl]},
   {env, []},
   {mod, {${ARTIFACT}, []}},
   {start_phases, []}]}.